spring.application.name=api
server.port=4400

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:taynote}
spring.datasource.username=${DB_USER:taynote}
spring.datasource.password=${DB_PASSWORD:taynote}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

